from fingro.compositions.compose_functions.pair_filters.homomorphism_pair_filter import homomorphism_pair_filter
from fingro.compositions.compose_functions.pair_filters.monomorphism_pair_filter import monomorphism_pair_filter
from fingro.compositions.compose_functions.pair_filters.isomorphism_pair_filter import isomorphism_pair_filter
