from fingro.compositions.compose_functions.pair_filters.homomorfism_pair_filter import homomorfism_pair_filter
from fingro.compositions.compose_functions.pair_filters.isomorfism_pair_filter import isomorfism_pair_filter
